system_prompt = "You will generate vector graphics via SVG code. We will apply a reinforcement learning approach, where feedback will be provided in every iteration, and you will improve upon the vector graphic accordingly."

user_prompt = "Generate simplistic SVG code representing a {object}. Ensure the SVG is of size 128x128."

feedback_prompt = "The attached image is the current output for a {object} generated by GPT using SVG code. Please provide concise feedback focusing on a single key aspect that needs improvement to better represent the described object. In particular, if a certain feature is missing, or a feature has been drawn in the incorrect location, suggest to fix the feature. Provide only one very short sentence."
